merge dotfiles_extra, start with templates

diff --git a/dot_zsh/functions.zsh.tmpl b/dot_zsh/functions.zsh.tmpl
--- a/dot_zsh/functions.zsh.tmpl
+++ b/dot_zsh/functions.zsh.tmpl
@@ -236,3 +236,72 @@ function printcolors() {
     print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}
   done
 }
+
+function wping() {
+    [ -n "$1" ] || return
+    ARG=${1}
+    TARGET=${ARG#*@}
+    TIMEOUT=2
+    COUNT=0
+    echo "retrying until $TARGET (from $ARG) becomes reachable..."
+    timeout $TIMEOUT ping -c 1 $TARGET &> /dev/null
+    while [ ! $? -eq 0 ]; do
+        # echo -en "."
+        let COUNT=COUNT+1
+        sleep 1
+        timeout $TIMEOUT ping -c 1 $TARGET &> /dev/null
+    done
+    [ $COUNT -gt 0 ] && echo ""
+}
+
+function wnping() {
+    [ -n "$1" ] || return
+    ARG=${1}
+    TARGET=${ARG#*@}
+    TIMEOUT=2
+    COUNT=0
+    echo "retrying until $TARGET (from $ARG) becomes unreachable..."
+    timeout $TIMEOUT ping -c 1 $TARGET &> /dev/null
+    while [ ! $? -ne 0 ]; do
+        # echo -en "."
+        let COUNT=COUNT+1
+        sleep 1
+        timeout $TIMEOUT ping -c 1 $TARGET &> /dev/null
+    done
+    [ $COUNT -gt 0 ] && echo ""
+}
+
+{{- if eq .chezmoi.os "linux" -}}
+function mzip() {
+  TARGET=/home/konni
+  if [ -n "$2" ];
+  then
+    TARGET="$HOME/Cloud/xkonni/share/$2"
+    # mkdir -p "$TARGET"
+  fi
+  if [ ! -e "$1" ];
+  then
+    echo "target \"$1\" does not exist"
+    return 1
+  fi
+
+  NAME=$(echo $1 | sed 's/\//-/g;s/ /_/g;s/\&/and/g;s/\[//g;s/\]//g;s/{//g;s/}//g')
+  echo "compressing \"$1\" to \"${TARGET}/${NAME}.zip\""
+  zip -r "${TARGET}/${NAME}.zip" "$1"
+}
+
+function publish() {
+  URLBASE=dump
+  [ -f "$1" ] || return
+  TARGET="$(basename $1 | sed 's/\ /_/g;s/(//;s/)//g')"
+  URL="https://xkonni.de/${URLBASE}/${TARGET}"
+  echo $URL
+  [ -e /usr/bin/xsel ] && echo $URL | xsel -pi 2> /dev/null
+  scp "$1" "xkonni:${URLBASE}/${TARGET}"
+  ssh xkonni chmod o+r "${URLBASE}/${TARGET}"
+  # cleanup
+  unset URLBASE
+  unset URL
+  unset TARGET
+}
+{{- end }}
