zsh: update

diff --git a/dot_zsh/u8s.zsh.tmpl b/dot_zsh/u8s.zsh.tmpl
--- a/dot_zsh/u8s.zsh.tmpl
+++ b/dot_zsh/u8s.zsh.tmpl
@@ -13,10 +13,89 @@ alias kl="u8s kubectl -- logs"
 alias klf="u8s kubectl -- logs -f"
 alias kg="u8s kubectl -- get"
 alias kga="u8s kubectl -- get --all-namespaces"
+alias kgm="u8s kubectl -- get -n metal-servers"
 alias kgp="u8s kubectl -- get pods -o wide"
 alias kgpa="u8s kubectl -- get pods -o wide --all-namespaces"
 alias kgn="u8s kubectl -- get nodes -L container-linux-update.v1.coreos.com/version -L failure-domain.beta.kubernetes.io/zone"
 alias kdn="u8s kubectl -- describe node"
 alias kdp="u8s kubectl -- describe pod"
 alias kds="u8s kubectl -- describe service"
+
+alias -g OY="-o yaml"
+alias -g OYL="-o yaml | bat -l yaml"
+alias -g OW="-o wide"
+
+function metal-eval() {
+    if [ -z "$KUBECONFIG" ]; then
+        echo "kubectl KUBECONFIG missing, exiting." >&2
+        return 1
+    fi
+    echo ">> metal-eval in $KUBECTL_CONTEXT"
+    read mns mpod mcont <<<$(kubectl get pods --all-namespaces -o wide | grep 'metal-operator-controller-manager' | awk '{print $1, $2, $8}')
+    read bns bpod bcont <<<$(kubectl get pods --all-namespaces -o wide | grep 'boot-operator-controller-manager' | awk '{print $1, $2, $8}')
+    read dns dpod dcont <<<$(kubectl get pods --all-namespaces -o wide | grep 'metal-operator-dnsmasq' | awk '{print $1, $2, $8}')
+    printf ">> %-15s\n>  %3s=%20s %4s=%50s %5s=%s\n" \
+        "metal-operator" mns "$mns" mpod "$mpod" mcont "$mcont"
+    printf ">> %-15s\n>  %3s=%20s %4s=%50s %5s=%s\n" \
+        "boot-operator" bns "$bns" bpod "$bpod" bcont "$bcont"
+    printf ">> %-15s\n>  %3s=%20s %4s=%50s %5s=%s\n" \
+        "dnsmasq" dns "$dns" dpod "$dpod" dcont "$dcont"
+    export mns mpod mcont bns bpod bcont dns dpod dcont
+}
+
+function _kube-logs() {
+    if [ $# -lt 2 ]; then
+        echo "Usage: _kube-logs <namespace> <podname>" >&2
+        return 1
+    fi
+    ns=$1
+    pod=$2
+    shift 2
+    if [ -z "$KUBECONFIG" ]; then
+        echo "kubectl KUBECONFIG missing, exiting." >&2
+        return 1
+    fi
+    LOGFILE=$HOME/log/$(date +%Y%m%d_%H%M%S)_${pod}.log
+    trap 'echo -e "\n\n> aborted.\n> logs saved to $LOGFILE"; return' INT
+    kubectl logs $* -n $ns $pod 2>&1 | tee $LOGFILE
+    [ $? ] && echo -e "\n\n> logs saved to $LOGFILE"
+    trap - INT
+}
+
+function k-metalop-logs() {
+    if [ -z "$mns" ] || [ -z "$mpod" ]; then
+        echo "metal-eval not run or failed, run metal-eval first." >&2
+        return 1
+    fi
+    _kube-logs $mns $mpod $*
+}
+
+function k-save-metalop-logs() {
+    LOGFILE=$HOME/log/$(date +%Y%m%d_%H%M%S)_${KUBECTL_CONTEXT}_${mns}_${mpod}.log
+    metalop-logs >$LOGFILE
+    [ $? ] && echo -e "> logs saved to $LOGFILE"
+}
+
+function k-bootop-logs() {
+    if [ -z "$bns" ] || [ -z "$bpod" ]; then
+        echo "metal-eval not run or failed, run metal-eval first." >&2
+        return 1
+    fi
+    _kube-logs $bns $bpod $*
+}
+
+function k-save-bootop-logs() {
+    LOGFILE=$HOME/log/$(date +%Y%m%d_%H%M%S)_${KUBECTL_CONTEXT}_${bns}_${bpod}.log
+    bootop-logs >$LOGFILE
+    [ $? ] && echo -e "> logs saved to $LOGFILE"
+}
+
+function k-get-leases() {
+    if [ -z "$dns" ] || [ -z "$dpod" ]; then
+        echo "metal-eval not run or failed, run metal-eval first." >&2
+        return 1
+    fi
+    echo "> leases from ns: \"$dns\" pod: \"$dpod\" /var/lib/misc/dnsmasq.leases:"
+    kubectl exec -it -n $dns $dpod -- cat /var/lib/misc/dnsmasq.leases
+}
 {{- end }}
